import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const watch = process.argv[2] === '--watch';

// Obsidian vault plugin directory
let OBSIDIAN_PLUGIN_DIR = process.env.OBSIDIAN_PLUGIN_DIR;
try {
  const envContent = fs.readFileSync('.env', 'utf8');
  const match = envContent.match(/^OBSIDIAN_PLUGIN_DIR=(.*)$/m);
  if (match) {
    OBSIDIAN_PLUGIN_DIR = match[1].trim();
  }
} catch (e) {
  // Ignore if .env doesn't exist
}

// Plugin to copy files to Obsidian after build
const copyPlugin = {
  name: 'copy-to-obsidian',
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) {
        console.error('❌ Build failed, skipping copy');
        return;
      }

      try {
        if (!OBSIDIAN_PLUGIN_DIR) {
          console.log('ℹ️ OBSIDIAN_PLUGIN_DIR is not set, skipping copy to Obsidian vault');
          return;
        }

        // Ensure directory exists
        if (!fs.existsSync(OBSIDIAN_PLUGIN_DIR)) {
          fs.mkdirSync(OBSIDIAN_PLUGIN_DIR, { recursive: true });
        }

        // Copy main.js
        fs.copyFileSync('main.js', path.join(OBSIDIAN_PLUGIN_DIR, 'main.js'));

        // Copy manifest.json from root
        fs.copyFileSync('../../manifest.json', path.join(OBSIDIAN_PLUGIN_DIR, 'manifest.json'));

        // Copy styles.css
        fs.copyFileSync('styles.css', path.join(OBSIDIAN_PLUGIN_DIR, 'styles.css'));

        console.log('✅ Files copied to Obsidian plugin directory');
      } catch (error) {
        console.error('❌ Error copying files:', error.message);
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  plugins: [copyPlugin],
});

if (watch) {
  await context.watch();
} else {
  await context.rebuild();
  await context.dispose();
}
